---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/tomw/nornir/netdevops/hosts.yaml"
        group_file: "/home/tomw/nornir/netdevops/groups.yaml"
        defaults_file: "/home/tomw/nornir/netdevops/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 100
