---
#[Providers]
CSR1:
    hostname: 192.168.100.101
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

CSR2:
    hostname: 192.168.100.102
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

CSR3:
    hostname: 192.168.100.103
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

CSR4:
    hostname: 192.168.100.104
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

CSR5:
    hostname: 192.168.100.105
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

CSR6:
    hostname: 192.168.100.106
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

#[Customer Devices]
vIOS7:
    hostname: 192.168.100.107
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: vios
        igp: ospf
        egp: bgp

vIOS8:
    hostname: 192.168.100.108
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: vios
        igp: ospf
        egp: bgp

vIOS9:
    hostname: 192.168.100.109
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: vios
        igp: ospf
        egp: bgp

vIOS10:
    hostname: 192.168.100.110
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: vios
        igp: ospf
        egp: bgp

#[Junos OS Devices]
vMX11:
    hostname: 192.168.100.111
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp

vMX12:
    hostname: 192.168.100.112
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp

vMX13:
    hostname: 192.168.100.113
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp