---
core:
  num_workers: 100


inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "/home/tomw/nornir/hosts.yaml"
    group_file: "/home/tomw/nornir/groups.yaml"
    defaults_file: "home/tomw/nornir/defalts/yaml"
