---
R1: 
    hostname: 192.168.100.101
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - area1

R2: 
    hostname: 192.168.100.102
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - area1

R3: 
    hostname: 192.168.100.103
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - area1

R4: 
    hostname: 192.168.100.104
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - area1

R5: 
    hostname: 192.168.100.105
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - area2

R6: 
    hostname: 192.168.100.106
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - area2

R7: 
    hostname: 192.168.100.107
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - area2

R8: 
    hostname: 192.168.100.108
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - area2

R11: 
    hostname: 192.168.100.111
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - green

R12: 
    hostname: 192.168.100.112
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - red

R13: 
    hostname: 192.168.100.113
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - blue

R14: 
    hostname: 192.168.100.114
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups: 
        - cisco_group
        - blue
