---
#[Providers]

CSR12:
    hostname: 192.168.100.132
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

CSR13:
    hostname: 192.168.100.133
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

CSR4:
    hostname: 192.168.100.134
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

CSR5:
    hostname: 192.168.100.105
    platform: 'ios'
    username: tomw
    password: mR7h0M@$
    groups:
        - cisco_group
    data:
        router_type: csr
        igp: ospf
        egp: bgp

#[Junos OS Devices]
vMX11:
    hostname: 192.168.100.121
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp

vMX12:
    hostname: 192.168.100.122
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp

vMX13:
    hostname: 192.168.100.123
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp
vMX14:
    hostname: 192.168.100.124
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp

vMX15:
    hostname: 192.168.100.125
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp

vMX16:
    hostname: 192.168.100.126
    platform: 'junos'
    username: tomw
    password: mR7h0M@$
    groups:
        - juniper_group
    data:
        router_type: vMX
        igp: ospf
        egp: bgp